package byt.money.moneymanager.gui.workingpanel;

import java.util.ResourceBundle;

/**
 *
 * @author Lukasz
 */
public class AddingManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddingManagerPanel
     */
    public AddingManagerPanel() {
        initComponents();
        localize();
    }

    public final void localize() {
        ResourceBundle I18N = ResourceBundle.getBundle("i18n/i18n");
        setBorder(javax.swing.BorderFactory.createTitledBorder(I18N.getString("AddingManagerPanelTitle")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        addingPanel1 = new byt.money.moneymanager.gui.workingpanel.AddingPanel();
        dynamicHistoryPanel1 = new byt.money.moneymanager.gui.workingpanel.DynamicHistoryPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Adding"));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        add(addingPanel1, gridBagConstraints);

        dynamicHistoryPanel1.setMinimumSize(new java.awt.Dimension(160, 160));
        dynamicHistoryPanel1.setPreferredSize(new java.awt.Dimension(160, 160));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weighty = 1.0;
        add(dynamicHistoryPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public AddingPanel getAddingPanel() {
        return addingPanel1;
    }

    public DynamicHistoryPanel getDynamicHistoryPanel() {
        return dynamicHistoryPanel1;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private byt.money.moneymanager.gui.workingpanel.AddingPanel addingPanel1;
    private byt.money.moneymanager.gui.workingpanel.DynamicHistoryPanel dynamicHistoryPanel1;
    // End of variables declaration//GEN-END:variables
}
