package byt.money.moneymanager.gui.workingpanel;

import byt.money.moneymanager.model.EventModel;
import java.awt.GridBagConstraints;
import java.util.List;

/**
 *
 * @author Lukasz
 */
public class DynamicHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form DynamicHistoryPanel
     */
    public DynamicHistoryPanel() {
        initComponents();
    }

    public void update(List<EventModel> lastFiveElements) {
        removeAll();
        for (int i = 0; i < lastFiveElements.size(); i++) {
            boolean lastElement = lastFiveElements.indexOf(lastFiveElements.get(i)) == lastFiveElements.size() - 1;
            GridBagConstraints gridBagConstraints = new GridBagConstraints();
            gridBagConstraints.gridy = i;
            gridBagConstraints.gridx = 0;
            gridBagConstraints.anchor = GridBagConstraints.FIRST_LINE_START;
            if (lastElement) {
                gridBagConstraints.weighty = 1;
            }
            OneDynamicPanel panel = new OneDynamicPanel();
            panel.update(lastFiveElements.get(i));
            add(panel, gridBagConstraints);
        }
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
