package byt.money.moneymanager.gui.workingpanel;

import byt.money.moneymanager.model.Event;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Lukasz
 */
public class FilterPanel extends javax.swing.JPanel {

    private Map<String, Event> localizeCB;

    /**
     * Creates new form FilterPanel
     */
    public FilterPanel() {
        initComponents();
    }

    public final void localize() {
        ResourceBundle I18N = ResourceBundle.getBundle("i18n/i18n");
        minAmountLabel.setText(I18N.getString("FilterPanel.minAmountLabel"));
        maxAmountLabel.setText(I18N.getString("FilterPanel.maxAmountLabel"));
        fromDateLabel.setText(I18N.getString("FilterPanel.fromDateLabel"));
        patternLabel.setText(I18N.getString("FilterPanel.patternLabel"));
        toDateLabel.setText(I18N.getString("FilterPanel.toDateLabel"));
        typeLabel.setText(I18N.getString("FilterPanel.typeLabel"));
        acceptButton.setText(I18N.getString("FilterPanel.acceptButton"));
        prepareCategoryField(I18N);
    }

    private void prepareCategoryField(ResourceBundle I18N) {
        localizeCB = new HashMap<>();
        String expenses = I18N.getString("AddingPanel.expenses");
        String inflow = I18N.getString("AddingPanel.inflow");
        String deposit = I18N.getString("AddingPanel.deposit");
        localizeCB.put(expenses, Event.EXPENSES);
        localizeCB.put(inflow, Event.INFLOW);
        localizeCB.put(deposit, Event.DEPOSIT);
        typeField.setModel(new DefaultComboBoxModel<>(new String[]{"", expenses, inflow, deposit}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        typeLabel = new javax.swing.JLabel();
        typeField = new javax.swing.JComboBox<>();
        minAmountLabel = new javax.swing.JLabel();
        minAmountField = new javax.swing.JTextField();
        patternLabel = new javax.swing.JLabel();
        patternField = new javax.swing.JTextField();
        fromDateLabel = new javax.swing.JLabel();
        fromDateField = new byt.money.moneymanager.gui.component.CalendarPanel();
        toDateLabel = new javax.swing.JLabel();
        toDateField = new byt.money.moneymanager.gui.component.CalendarPanel();
        maxAmountLabel = new javax.swing.JLabel();
        maxAmountField = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        typeLabel.setText("Type:");
        typeLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        typeLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        typeLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(typeLabel, gridBagConstraints);

        typeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeField.setMinimumSize(new java.awt.Dimension(120, 30));
        typeField.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(typeField, gridBagConstraints);

        minAmountLabel.setText("Min. amount:");
        minAmountLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        minAmountLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        minAmountLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(minAmountLabel, gridBagConstraints);

        minAmountField.setMinimumSize(new java.awt.Dimension(120, 30));
        minAmountField.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(minAmountField, gridBagConstraints);

        patternLabel.setText("Wzorzec:");
        patternLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        patternLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        patternLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(patternLabel, gridBagConstraints);

        patternField.setMinimumSize(new java.awt.Dimension(120, 30));
        patternField.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(patternField, gridBagConstraints);

        fromDateLabel.setText("From date:");
        fromDateLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        fromDateLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        fromDateLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(fromDateLabel, gridBagConstraints);

        fromDateField.setMinimumSize(new java.awt.Dimension(202, 30));
        fromDateField.setPreferredSize(new java.awt.Dimension(202, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(fromDateField, gridBagConstraints);

        toDateLabel.setText("To date:");
        toDateLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        toDateLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        toDateLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(toDateLabel, gridBagConstraints);

        toDateField.setMinimumSize(new java.awt.Dimension(202, 30));
        toDateField.setPreferredSize(new java.awt.Dimension(202, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        add(toDateField, gridBagConstraints);

        maxAmountLabel.setText("Max. amount:");
        maxAmountLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        maxAmountLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        maxAmountLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(maxAmountLabel, gridBagConstraints);

        maxAmountField.setMinimumSize(new java.awt.Dimension(120, 30));
        maxAmountField.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(maxAmountField, gridBagConstraints);

        acceptButton.setText("Accept");
        acceptButton.setMaximumSize(new java.awt.Dimension(120, 30));
        acceptButton.setMinimumSize(new java.awt.Dimension(120, 30));
        acceptButton.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(acceptButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private byt.money.moneymanager.gui.component.CalendarPanel fromDateField;
    private javax.swing.JLabel fromDateLabel;
    private javax.swing.JTextField maxAmountField;
    private javax.swing.JLabel maxAmountLabel;
    private javax.swing.JTextField minAmountField;
    private javax.swing.JLabel minAmountLabel;
    private javax.swing.JTextField patternField;
    private javax.swing.JLabel patternLabel;
    private byt.money.moneymanager.gui.component.CalendarPanel toDateField;
    private javax.swing.JLabel toDateLabel;
    private javax.swing.JComboBox<String> typeField;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
