package byt.money.moneymanager.gui.workingpanel;

import java.util.ResourceBundle;

/**
 *
 * @author Lukasz
 */
public class WelcomePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
        localize();
    }
    
    public final void localize(){
        ResourceBundle I18N = ResourceBundle.getBundle("i18n/i18n");
        setBorder(javax.swing.BorderFactory.createTitledBorder(I18N.getString("WelcomePanelTitle")));
    }
    
    public void update(String text){
        ResourceBundle I18N = ResourceBundle.getBundle("i18n/i18n");
        messageLabel.setText(I18N.getString("WelcomePanel.welcome")+text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        messageLabel.setMaximumSize(new java.awt.Dimension(120, 24));
        messageLabel.setMinimumSize(new java.awt.Dimension(120, 24));
        messageLabel.setPreferredSize(new java.awt.Dimension(120, 24));
        add(messageLabel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
