package byt.money.moneymanager.gui;

import java.util.ResourceBundle;

/**
 *
 * @author Lukasz
 */
public class ButtonBarPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ButtonBarPanel
     */
    public ButtonBarPanel() {
        initComponents();
        localize();
    }
    
    public final void localize(){
        ResourceBundle I18N = ResourceBundle.getBundle("i18n/i18n");
        setBorder(javax.swing.BorderFactory.createTitledBorder(I18N.getString("ButtonBarPanelTitle")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Mode panel"));
        setMaximumSize(new java.awt.Dimension(70, 70));
        setMinimumSize(new java.awt.Dimension(70, 70));
        setPreferredSize(new java.awt.Dimension(70, 70));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
